# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PluginsIgnSia
                                 A QGIS plugin
 Les plugins utilisés au SIA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-03-12
        copyright            : (C) 2018 by Equipe produit Imagerie et departement de la photogrammetrie
        email                : renaud.burck@ign.fr ou tout_pap@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Equipe produit Imagerie et departement de la photogrammetrie'
__date__ = '2018-03-12'
__copyright__ = '(C) 2018 by Equipe produit Imagerie et departement de la photogrammetrie'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PluginsIgnSia class from file PluginsIgnSia.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .IGN_SIA import PluginsIgnSiaPlugin
    return PluginsIgnSiaPlugin()
